CREATE PROC KITAP_Insert
@ADI NVARCHAR(150),
@YAZAR NVARCHAR(150),
@SAYFASAYISI SMALLINT,
@KATEGORIID INT
AS
INSERT INTO KITAP(ADI,YAZAR,SAYFASAYISI,KATEGORIID )
 VALUES (@ADI,@YAZAR,@SAYFASAYISI,@KATEGORIID)

GO

CREATE PROC KITAP_Update
@ID INT,
@ADI NVARCHAR(150),
@YAZAR NVARCHAR(150),
@SAYFASAYISI SMALLINT,
@KATEGORIID INT
AS
UPDATE KITAP 
SET ADI=@ADI, YAZAR=@YAZAR,SAYFASAYISI=@SAYFASAYISI,KATEGORIID=@KATEGORIID WHERE ID=@ID

GO

CREATE PROC KITAP_Delete
@ID INT
AS
DELETE FROM KITAP WHERE ID=@ID

GO

CREATE PROC KITAP_Select
@ID INT
AS
SELECT * FROM KITAP T1 WITH(NOLOCK) WHERE T1.ID=@ID

GO

CREATE PROC KITAP_SelectList
AS
SELECT * FROM KITAP WITH(NOLOCK)
